### ISSUE TITLE
I have no way to use it anymore TAT

### ISSUE THREAD

**Issue by 1419427247** [PawanOsman/ChatGPT.Net#14]
![image](https://user-images.githubusercontent.com/33598732/220902636-8d9ac8cc-9dec-425a-86b7-7354cea40fce.png)

**Comment by PawanOsman** [comment]
I just checked and it works fine, make sure your session token is valid and isn't expired,

and make sure your config file does not contain a conversation from another account (means if you changed your session token to another account it may be not working because the new session token can't access the other account conversations and you need to delete the conversation file too)

**Comment by 1419427247** [comment]
> I just checked and it works fine, make sure your session token is valid and isn't expired,
> 
> and make sure your config file does not contain a conversation from another account (means if you changed your session token to another account it may be not working because the new session token can't access the other account conversations and you need to delete the conversation file too)

Thank you for your answer, although I don't know why, I changed the SessionToken in the code and it didn't work, I just deleted the default-ChatGPT-Net.json file and the program works fine!
