### ISSUE TITLE
Converting to .NET Framework only

### ISSUE THREAD

**Issue by securigy** [PawanOsman/ChatGPT.Net#4]
How difficult or effortless is to convert the project to be compatible to .NET Framework (4.7.2-4.8)?
I am trying to make a plug-in for a big project that is incompatible with .NET Standard/Core/6.0/7.0 and will never be... So my only way is to downgrade ChatGPT.Net to .NET Framework. What does it involve specifically?

**Comment by PawanOsman** [comment]
The project is based on .NET Core, and converting it to older versions of the .NET Framework requires a separate project because it cannot be easily done in a single project.

I attempted to add .NET Standard 2.0 and used a .NET 4.7.2 project, but it did not work. This means that more modifications are needed to make it work with .NET Framework 4.7.2 or 4.8.
